python 3: add FutureModel class to downgrade newstr prop values to native_str
...since App Engine's protobuf library chokes on future.types.newstr.newstr property values:

```
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 256, in _MakeRealSyncCall
    raise pickle.loads(response_pb.exception())
RuntimeError: ProtocolBufferDecodeError('truncated',)
```