util.is_connection_failure(): handle tweepy error on max retries failed
specifically:

```
tweepy.error.TweepError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /oauth/request_token?x_auth_access_type=read (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x3e5ed28e8070>: Failed to establish a new connection: [Errno 110] Connection timed out'))

  at get_authorization_url (/layers/google.python.pip/pip/lib/python3.8/site-packages/tweepy/auth.py:94)
...
```

fixes https://console.cloud.google.com/errors/CPnSx-yemJ-hlAE